# Shared Role for CSI driver operators to read Secrets from openshift-config namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csi-driver-operator-config-secrets-reader
  namespace: openshift-config
rules:
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
