# Creating the namespace in cluster-storage-operator to simplify ReplatedObjects
# composition - cluster-storage-operator needs to know what namespaces to add
# there.
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-manila-csi-driver
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
    workload.openshift.io/allowed: "management"
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
