apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  name: manila.csi.openstack.org
  annotations:
    storage.openshift.io/remove-from: mgmt
spec:
  managementState: Managed
  logLevel: Normal
  operatorLogLevel: Normal
