apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-disk-csi-driver-operator
spec:
  template:
    spec:
      priorityClassName: system-cluster-critical
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: "NoSchedule"
      containers:
      - name: azure-disk-csi-driver-operator
        volumeMounts:
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: azure-disk-csi-driver-operator-serving-cert
