apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powervs-block-csi-driver-operator-clusterrole
rules:
- apiGroups:
  - cloudcredential.openshift.io
  resources:
  - credentialsrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.storage.k8s.io
  resources:
  - csinodeinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - openshift-csi-main-attacher-role
  - openshift-csi-main-provisioner-role
  - openshift-csi-main-resizer-role
  - openshift-csi-provisioner-volumesnapshot-reader-role
  - openshift-csi-resizer-storageclass-reader-role
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - storage.openshift.io
  resources:
  - powervsblockcsidrivers/status
  verbs:
  - patch
  - update
