apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcp-pd-csi-driver-operator-clusterrole
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - hostnetwork-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - openshift-csi-main-attacher-role
  - openshift-csi-main-provisioner-role
  - openshift-csi-main-resizer-role
  - openshift-csi-main-snapshotter-role
  - openshift-csi-provisioner-volumeattributesclass-reader-role
  - openshift-csi-provisioner-volumesnapshot-reader-role
  - openshift-csi-resizer-storageclass-reader-role
  - openshift-csi-resizer-volumeattributesclass-reader-role
  resources:
  - clusterroles
  verbs:
  - bind
