# Allow Azure File CSI driver operator to read Secrets from openshift-config namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-file-csi-driver-operator-secrets-reader-role
  namespace: openshift-config
rules:
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
