apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  name: cinder.csi.openstack.org
  annotations:
    storage.openshift.io/remove-from: mgmt
spec:
  managementState: Managed
  logLevel: Trace
  operatorLogLevel: Trace
  driverConfig:
    driverName: cinder.csi.openstack.org
