apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-ebs-csi-driver-operator-config
  namespace: openshift-cluster-csi-drivers
  annotations:
    storage.openshift.io/remove-from: guest
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
