apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  annotations:
    storage.openshift.io/remove-from: mgmt
  name: pd.csi.storage.gke.io
  namespace: openshift-cluster-csi-drivers
spec:
  logLevel: Normal
  managementState: Managed
  operatorLogLevel: Normal
