apiVersion: v1
kind: ConfigMap
metadata:
  name: powervs-block-csi-driver-operator-config
  namespace: openshift-cluster-csi-drivers
  annotations:
    config.openshift.io/inject-tls: "true"
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
