apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.openshift.io/inject-proxy: manila-csi-driver-operator
    release.openshift.io/desired-version: ${RELEASE_VERSION}
    storage.openshift.io/remove-from: guest
  labels:
    hypershift.openshift.io/managed-by: cluster-storage-operator
  name: manila-csi-driver-operator
  namespace: ${CONTROLPLANE_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manila-csi-driver-operator
  strategy: {}
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: manila-csi-driver-operator
        hypershift.openshift.io/need-management-kas-access: "true"
        name: manila-csi-driver-operator
        openshift.storage.network-policy.all-egress: allow
        openshift.storage.network-policy.api-server: allow
        openshift.storage.network-policy.dns: allow
        openshift.storage.network-policy.operator-metrics-range: allow
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: hypershift.openshift.io/control-plane
                operator: In
                values:
                - "true"
            weight: 50
          - preference:
              matchExpressions:
              - key: hypershift.openshift.io/cluster
                operator: In
                values:
                - ${CONTROLPLANE_NAMESPACE}
            weight: 100
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  hypershift.openshift.io/hosted-control-plane: ${CONTROLPLANE_NAMESPACE}
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - start
        - -v=${LOG_LEVEL}
        - --guest-kubeconfig=/etc/guest-kubeconfig/kubeconfig
        env:
        - name: DRIVER_CONTROL_PLANE_IMAGE
          value: ${DRIVER_CONTROL_PLANE_IMAGE}
        - name: LIVENESS_PROBE_CONTROL_PLANE_IMAGE
          value: ${LIVENESS_PROBE_CONTROL_PLANE_IMAGE}
        - name: DRIVER_IMAGE
          value: ${DRIVER_IMAGE}
        - name: NFS_DRIVER_IMAGE
          value: ${NFS_DRIVER_IMAGE}
        - name: PROVISIONER_IMAGE
          value: ${PROVISIONER_IMAGE}
        - name: ATTACHER_IMAGE
          value: ${ATTACHER_IMAGE}
        - name: RESIZER_IMAGE
          value: ${RESIZER_IMAGE}
        - name: SNAPSHOTTER_IMAGE
          value: ${SNAPSHOTTER_IMAGE}
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: ${NODE_DRIVER_REGISTRAR_IMAGE}
        - name: LIVENESS_PROBE_IMAGE
          value: ${LIVENESS_PROBE_IMAGE}
        - name: KUBE_RBAC_PROXY_IMAGE
          value: ${KUBE_RBAC_PROXY_IMAGE}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ${OPERATOR_IMAGE}
        imagePullPolicy: IfNotPresent
        name: manila-csi-driver-operator
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/guest-kubeconfig
          name: guest-kubeconfig
        - mountPath: /etc/openstack
          name: cloud-credentials
          readOnly: true
        - mountPath: /etc/openstack-ca
          name: legacy-cacert
          readOnly: true
        - mountPath: /tmp
          name: tmp
      priorityClassName: hypershift-control-plane
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: manila-csi-driver-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - key: hypershift.openshift.io/control-plane
        operator: Exists
      - key: hypershift.openshift.io/cluster
        operator: Equal
        value: ${CONTROLPLANE_NAMESPACE}
      volumes:
      - name: guest-kubeconfig
        secret:
          secretName: service-network-admin-kubeconfig
      - configMap:
          items:
          - key: ca-bundle.pem
            path: ca-bundle.pem
          name: openstack-cloud-config
          optional: true
        name: legacy-cacert
      - name: cloud-credentials
        projected:
          sources:
          - secret:
              items:
              - key: cacert
                path: ca.crt
              name: openstack-cloud-credentials
              optional: true
          - secret:
              items:
              - key: clouds.yaml
                path: clouds.yaml
              name: openstack-cloud-credentials
      - emptyDir:
          medium: Memory
        name: tmp
