apiVersion: v1
imagePullSecrets:
- name: pull-secret
kind: ServiceAccount
metadata:
  annotations:
    storage.openshift.io/remove-from: guest
  name: manila-csi-driver-operator
  namespace: ${CONTROLPLANE_NAMESPACE}
