# Create the namespace at runlevel 49, so cluster-csi-snapshot-controller-operator (running at level 50) can use it.
# We keep this namespace without capability name untill we merge cluster-csi-snapshot-controller capability
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    openshift.io/node-selector: ""
    workload.openshift.io/allowed: "management"
    capability.openshift.io/name: Storage+CSISnapshot
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-cluster-storage-operator
