# Create the namespace at runlevel 49, so cluster-csi-snapshot-controller-operator (running at level 50) can use it.
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
    include.release.openshift.io/single-node-production-edge: "true"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-cluster-storage-operator
