apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.vsphere.vmware.com
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
