apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: kubevirt-csi-driver-operator
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  secretRef:
    namespace: openshift-cluster-csi-drivers
    name: infra-cluster-credentials
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: KubevirtProviderSpec