apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-gcp-pd-csi-driver-operator
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Storage+CloudCredential
spec:
  serviceAccountNames:
  - gcp-pd-csi-driver-operator
  - gcp-pd-csi-driver-controller-sa
  secretRef:
    name: gcp-pd-cloud-credentials
    namespace: openshift-cluster-csi-drivers
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    # Required driver permissions: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/1a1f846c41c963e17b4757ce3beb0bf1e817d473/docs/kubernetes/user-guides/driver-install.md?plain=1#L17-L21
    predefinedRoles:
      - "roles/compute.storageAdmin"
      - "roles/resourcemanager.tagUser"
    permissions:
      - "compute.instances.get"
      - "compute.instances.attachDisk"
      - "compute.instances.detachDisk"
      - "iam.serviceAccounts.actAs"
    # If set to true, don't check whether the requested
    # roles have the necessary services enabled
    skipServiceCheck: true
