apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: azure-file-csi-driver-operator
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Storage+CloudCredential
spec:
  serviceAccountNames:
  - azure-file-csi-driver-operator
  - azure-file-csi-driver-controller-sa
  - azure-file-csi-driver-node-sa
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
      - 'Microsoft.Network/networkSecurityGroups/join/action'
      - 'Microsoft.Network/routeTables/join/action'
      - 'Microsoft.Network/natGateways/join/action'
      - 'Microsoft.Network/virtualNetworks/subnets/read'
      - 'Microsoft.Network/virtualNetworks/subnets/write'
      - 'Microsoft.Storage/storageAccounts/delete'
      - 'Microsoft.Storage/storageAccounts/fileServices/read'
      - 'Microsoft.Storage/storageAccounts/fileServices/shares/delete'
      - 'Microsoft.Storage/storageAccounts/fileServices/shares/read'
      - 'Microsoft.Storage/storageAccounts/fileServices/shares/write'
      - 'Microsoft.Storage/storageAccounts/listKeys/action'
      - 'Microsoft.Storage/storageAccounts/read'
      - 'Microsoft.Storage/storageAccounts/write'
  secretRef:
    name: azure-file-credentials
    namespace: openshift-cluster-csi-drivers

