apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: kubevirt-csi-driver-operator
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    namespace: openshift-cluster-csi-drivers
    name: infra-cluster-credentials
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: KubevirtProviderSpec