apiVersion: operator.openshift.io/v1
kind: Storage
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
    include.release.openshift.io/single-node-production-edge: "true"
spec:
  managementState: Managed
  logLevel: Normal
  operatorLogLevel: Normal
