kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator-role
  namespace: openshift-cluster-storage-operator
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-production-edge: "true"
subjects:
  - kind: ServiceAccount
    name: cluster-storage-operator
    namespace: openshift-cluster-storage-operator
roleRef:
  # TODO: rework to smaller roles
  kind: ClusterRole
  name: cluster-admin
