apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-resource-csi-driver-operator-role
  namespace: openshift-cluster-csi-drivers
rules:
- apiGroups:
  - 'sharedresource.openshift.io'
  resources:
  - sharedconfigmaps
  - sharedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - 'authorization.k8s.io'
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - update
  - patch
  - delete
