kind: Service
apiVersion: v1
metadata:
  name: shared-resource-csi-driver-operator-metrics
  namespace: openshift-cluster-csi-drivers
  labels:
    name: shared-resource-csi-driver-operator
spec:
  selector:
    name: shared-resource-csi-driver-operator
  ports:
    - name: metrics
      port: 6000
