apiVersion: apps/v1
kind: Deployment
metadata:
  name: manila-csi-driver-operator
  labels:
    hypershift.openshift.io/managed-by: cluster-storage-operator
  annotations:
    release.openshift.io/desired-version: ${RELEASE_VERSION}
spec:
  template:
    metadata:
      labels:
        app: manila-csi-driver-operator
        hypershift.openshift.io/need-management-kas-access: "true"
        openshift.storage.network-policy.all-egress: allow
        openshift.storage.network-policy.api-server: allow
        openshift.storage.network-policy.dns: allow
        openshift.storage.network-policy.operator-metrics-range: allow
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: hypershift.openshift.io/control-plane
                    operator: In
                    values:
                      - "true"
              weight: 50
            - preference:
                matchExpressions:
                  - key: hypershift.openshift.io/cluster
                    operator: In
                    values:
                      - ${CONTROLPLANE_NAMESPACE}
              weight: 100
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    hypershift.openshift.io/hosted-control-plane: ${CONTROLPLANE_NAMESPACE}
                topologyKey: kubernetes.io/hostname
              weight: 100
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: "NoSchedule"
        - key: hypershift.openshift.io/control-plane
          operator: Exists
        - key: hypershift.openshift.io/cluster
          operator: Equal
          value: ${CONTROLPLANE_NAMESPACE}
      containers:
      - name: manila-csi-driver-operator
        env:
          - name: DRIVER_CONTROL_PLANE_IMAGE
            value: ${DRIVER_CONTROL_PLANE_IMAGE}
          - name: LIVENESS_PROBE_CONTROL_PLANE_IMAGE
            value: ${LIVENESS_PROBE_CONTROL_PLANE_IMAGE}
        volumeMounts:
          - mountPath: /etc/guest-kubeconfig
            name: guest-kubeconfig
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          readOnlyRootFilesystem: false
      priorityClassName: hypershift-control-plane
      volumes:
        - name: guest-kubeconfig
          secret:
            secretName: service-network-admin-kubeconfig
        # This is the legacy location of the CA cert. The cert is now provided in
        # the credentials secret generated by cloud-credential-operator, so this
        # will not be used outside of an upgrade scenario
        # TODO(stephenfin): Remove in 4.20
        - name: legacy-cacert
          configMap:
            name: openstack-cloud-config
            items:
              - key: ca-bundle.pem
                path: ca-bundle.pem
            optional: true
