apiVersion: v1
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
kind: ConfigMap
metadata:
  annotations:
    config.openshift.io/inject-tls: "true"
  name: azure-file-csi-driver-operator-config
  namespace: openshift-cluster-csi-drivers
