apiVersion: v1
kind: ConfigMap
metadata:
  name: vmware-vsphere-csi-driver-operator-config
  namespace: openshift-cluster-csi-drivers
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
