apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vmware-vsphere-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
  labels:
    role: alert-rules
spec:
  groups:
    - name: vmware-vsphere-csi-driver-operator.rules
      rules:
      - alert: UnsupportedCSIDriverInstalled
        # Using min_over_time to make sure the metric is `1` for whole 5 minutes.
        # A missed scraping (e.g. due to a pod restart) will result in prometheus re-evaluating the the alerting rule.
        expr:  min_over_time(vsphere_csi_driver_error{condition="install_blocked",failure_reason="existing_driver_found"}[5m]) == 1
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Unsupported VSphere CSI driver installed"
          description: |
            OpenShift has detected that an unsupported version of vSphere CSI driver is installed.
            It is OK to use this CSI driver for now, however, Red Hat does not support it.
            In a future OpenShift version it will be required to use OpenShift's version of the CSI
            driver to correctly migrate vSphere PersistentVolumes to CSI. Please consult OpenShift
            release notes before upgrading to the next version.
            To get a version of the CSI driver supported by Red Hat, uninstall the CSI driver,
            including its Deployment, DaemonSet and CSIDriver objects and OpenShift will
            automatically install a supported version of the CSI driver.
          message: "An unsupported version of vSphere CSI driver installation detected."
      - alert: VSphereTopologyMisconfiguration
        # min() takes minimum over both source="infrastructure" and source="clustercsidriver"
        # dimensions and only when both are above zero the alert is triggered.
        expr:  min(vsphere_topology_tags{source=~"infrastructure|clustercsidriver"}) > 0
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "vSphere topology is erroneously configured both in ClusterCSIDriver and Infrastructure."
          description: |
            vSphere topology is configured both in vSphere ClusterCSIDriver and Infrastructure
            objects. The topology in ClusterCSIDriver is ignored and only the one in
            Infrastructure object is used to configure the vSphere CSI driver. Please delete
            topology in ClusterCSIDriver, for example by
            "oc edit clustercsidriver csi.vsphere.vmware.com" and removing the whole
            "topologyCategories" section.
          message: "vSphere topology is erroneously configured both in ClusterCSIDriver and Infrastructure objects, only the one in Infrastructure is used."

    # Rules to remove unnecessary labels before sending metrics through telemetry.
    - name: vmware-vsphere-csi-driver-operator-telemetry.rules
      rules:
      - expr: sum by(version)(vsphere_vcenter_info)
        record: cluster:vsphere_vcenter_info:sum
      - expr: sum by(version)(vsphere_esxi_version_total)
        record: cluster:vsphere_esxi_version_total:sum
      - expr: sum by(hw_version)(vsphere_node_hw_version_total)
        record: cluster:vsphere_node_hw_version_total:sum
      - expr: max by(source)(vsphere_topology_tags)
        record: cluster:vsphere_topology_tags:max
      - expr: max by(scope)(vsphere_infrastructure_failure_domains)
        record: cluster:vsphere_infrastructure_failure_domains:max
