kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shared-resource-csi-driver-operator-config-clusterrolebinding
  namespace: openshift-config-managed
subjects:
  - kind: ServiceAccount
    name: shared-resource-csi-driver-operator
    namespace: openshift-cluster-csi-drivers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-resource-csi-driver-operator-config-role
