apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-disk-csi-driver-operator-clusterrole
  annotations:
    storage.openshift.io/remove-from: mgmt
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  - featuregates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments/status
  verbs:
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattributesclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - azure-disk-csi-driver-operator-lock
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - openshift-csi-main-attacher-role
  - openshift-csi-main-provisioner-role
  - openshift-csi-main-resizer-role
  - openshift-csi-main-snapshotter-role
  - openshift-csi-provisioner-volumeattributesclass-reader-role
  - openshift-csi-provisioner-volumesnapshot-reader-role
  - openshift-csi-resizer-storageclass-reader-role
  - openshift-csi-resizer-volumeattributesclass-reader-role
  resources:
  - clusterroles
  verbs:
  - bind
