apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere-problem-detector-operator-config
  namespace: openshift-cluster-storage-operator
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
