apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  name: cinder.csi.openstack.org
  namespace: ${CONTROLPLANE_NAMESPACE}
spec:
  driverConfig:
    driverName: cinder.csi.openstack.org
  logLevel: Trace
  managementState: Managed
  operatorLogLevel: Trace
