kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-file-csi-driver-operator-common-rolebinding
  namespace: ${CONTROLPLANE_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: azure-file-csi-driver-operator
    namespace: ${CONTROLPLANE_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-driver-operator-common-role
