# Management-topology namespaced Role for HyperShift: CSI driver operators
# manipulate these namespaced objects only in ${CONTROLPLANE_NAMESPACE}.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csi-driver-operator-common-role
  namespace: ${CONTROLPLANE_NAMESPACE}
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
