# Namespaced counterpart of csi-driver-operator-common-role: CSI driver operators
# manipulate these namespaced objects only in openshift-cluster-csi-drivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csi-driver-operator-common-role
  namespace: openshift-cluster-csi-drivers
rules:
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
