apiVersion: v1
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
kind: ConfigMap
metadata:
  annotations:
    storage.openshift.io/remove-from: guest
  name: azure-disk-csi-driver-operator-config
  namespace: openshift-cluster-csi-drivers
